name: Style check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './src'
        exclude: './libs'
        extensions: 'h,cpp'
        clangFormatVersion: 8
